{...}: {
  imports = [
    ./auto-save
    ./bufferline
    ./cmp-path
    ./cmp-nvim-lsp
    ./cmp-nvim-lsp-document-symbol
    ./cmp-nvim-lsp-signature-help
    ./cmp_luasnip
    ./cursorline
    ./comment-nvim
    ./friendly-snippets
    ./lualine
    ./lsp
    ./lsp-format
    ./luasnip
    ./nvim-autopairs
    ./nvim-tree
    ./nvim-cmp
    ./nvim-colorizer
    ./gitsigns
    ./rustaceanvim
    ./indent-blankline
    ./rainbow-delimiters
    ./which-key
    ./vim-bbye
    ./project-nvim
    ./toggleterm
    ./telescope
    ./treesitter
    ./surround
  ];
}
