{...}: {
  imports = [
    ./alpha
    ./auto-save
    ./bufferline
    ./better-escape
    ./cmp
    ./cursorline
    ./conform-nvim
    ./comment
    ./crates-nvim
    ./dap
    ./dressing
    ./friendly-snippets
    ./fine-cmdline
    ./lualine
    ./haskell-tools-nvim
    ./hardtime
    ./lsp
    ./lspsaga
    ./luasnip
    ./nvim-autopairs
    ./nvim-tree
    ./neotest
    ./notify
    ./ts-autotag
    ./trouble
    ./nix-develop
    ./neodev
    ./nx
    ./nvim-colorizer
    ./mini
    ./leap
    ./tmux-navigator
    ./tagbar
    ./ts-context-commentstring
    ./searchbox
    ./gitsigns
    ./rustaceanvim
    ./indent-blankline
    ./rainbow-delimiters
    ./which-key
    ./vim-bbye
    ./project-nvim
    ./toggleterm
    ./telescope
    ./treesitter
    ./surround
    ./vimtex
  ];
}
