#!/usr/bin/env bash

mkdir -p ~/.config/sops/age
nix run nixpkgs#ssh-to-age -- -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
nix shell nixpkgs#age -c age-keygen -y ~/.config/sops/age/keys.txt
cd ~/.config/nixos/secrets || exit
nix shell nixpkgs#sops -c sops secrets.yaml

